listen = *
protocols = pop3 imap submission
disable_plaintext_auth = no
mail_location = maildir:/home/%u/mail
ssl = no
auth_mechanisms = plain login
auth_verbose = yes
first_valid_uid = 0

passdb {
  driver = passwd-file
  args = /etc/dovecot/users
}
userdb {
  driver = static
  args = uid=kullanici gid=kullanici home=/home/%u
}

service pop3-login {
  inet_listener pop3 {
    port = 110
  }
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}

service submission-login {
  inet_listener submission {
    port = 587
  }
}

submission_relay_host = 172.50.2.16
submission_relay_port = 1025
submission_relay_trusted = yes
