[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[1000]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=1000-auth
aors=1000

[1000-auth]
type=auth
auth_type=userpass
password=voip123
username=1000
realm=voip

[1000]
type=aor
max_contacts=1

[1001]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=1001-auth
aors=1001

[1001-auth]
type=auth
auth_type=userpass
password=voip456
username=1001
realm=voip

[1001]
type=aor
max_contacts=1
