FROM alpine:3.21

RUN apk add --no-cache vsftpd

RUN adduser -D -h /home/ftpuser -s /bin/sh ftpuser && \
    mkdir -p /home/ftpuser/uploads && \
    chown -R ftpuser:ftpuser /home/ftpuser && \
    mkdir -p /var/run/vsftpd/empty && \
    mkdir -p /usr/share/empty

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 21 21100-21110

ENTRYPOINT ["/entrypoint.sh"]
