FROM alpine:3.21

RUN apk add --no-cache \
    curl \
    nmap \
    nmap-scripts \
    netcat-openbsd \
    bash \
    iputils \
    tcpdump \
    bind-tools \
    python3

WORKDIR /tools
CMD ["sleep", "infinity"]
